exclude: ^tests/test_data/
exclude: ^mm_language_server/config/

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^tests/test_data/
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^tests/test_data/
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
        exclude: ^tests/test_data/
  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: poetry run docformatter --check
        language: system
        types: [python]
